First working version
wirenboard/modbus-utils-rpc pull request #1
Opened 2022-03-29 16:32 UTC by ekateluv

2022-03-29 18:08 UTC, webconn reviewed
Ещё можно добавить точку входа в каком-нибудь виде, чтобы можно было вызывать из консоли без магии в духе `python3 -m что-то-там`

2022-03-29 18:08 UTC, webconn commented on modbus-utils-rpc/main.py
> +parser = argparse.ArgumentParser()
Стоит всё это положить в функцию с именем `main`, а внизу сделать её вызов под 

```
if __name__ == "__main__":
  sys.exit(main(sys.argv))
```

Считается хорошим тоном, плюс позволяет переиспользовать код без запуска новых инстансов питона

2022-03-29 18:08 UTC, webconn commented on modbus-utils-rpc/main.py
> +def request_handling(args):
Лучше использовать простое настоящее время в именах функций/методов

2022-03-29 18:08 UTC, webconn commented on modbus-utils-rpc/main.py
> +        if (int(resp['result_code'])!=0):
В питоне не надо ставить скобочки вокруг условий в `if`, здесь и ниже. Можно натравить какой-нибудь питоновый линтер, хотя бы то, что в vscode есть, пусть он поругается и поправит что-нибудь сам

2022-03-29 18:08 UTC, webconn commented on modbus-utils-rpc/main.py
> +        mqttClient.loop_start()
Цикл нигде не останавливается, нехорошо. Рекомендую попробовать применить здесь `contextlib`, чтобы обернуть операции, требующие запущенного клиента, в `with ...`

2022-03-29 18:08 UTC, webconn commented on modbus-utils-rpc/main.py
> +                return;
Ну и как-то отрапортовать, что что-то пошло не так. Ещё важно, чтобы утилита возвращала ненулевой код возврата, если что-то пошло не так, и коды в идеале сопоставить с оными из modbus-utils хотя бы в простых случаях

2022-03-30 08:09 UTC, vdromanov commented on modbus-utils-rpc/main.py
> +def request_handling(args):
мне кажется, или тут везде отступы - не 4 пробела?

2022-04-05 09:57 UTC, webconn commented on modbus_utils_rpc/main.py
> +    USER_INPUT_ERROR = 1
Наоборот )

2022-04-05 09:57 UTC, webconn commented on modbus_utils_rpc/main.py
> +    sys.exit(int(main(sys.argv)))
А явное преобразование в `int` тут правда нужно?

2022-04-05 09:57 UTC, webconn commented on modbus_utils_rpc/main.py
> +def request_handle(args):
`handle` обычно про обработку внешнего события. Тут больше подойдёт слово `process`, и глагол стоит в начало ставить

2022-04-05 09:57 UTC, webconn commented on modbus_utils_rpc/main.py
> +def tcp_path_create(args):
Аналогично про имена, `create_tcp_path` читается проще (аналогично для rtu)

2022-04-05 10:18 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    sys.exit(int(main(sys.argv)))
Если без преобразования, то в консоль выводится сам енум, то есть прям строчка типа "ResultCode.OPERATION_ERROR". Мне показалось стремно показывать пользователю какие то внутренние названия структур. Если сделать int(), то ничего не выводит

2022-04-05 20:55 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +def main(argv=sys.argv):
а апи, как в модбас_клиенте мы не хотим сделать?
думаю, надо, т.к. люди привыкли за годы и понаписали баш-скриптов вокруг

а тут - чет прям совсем отличается

2022-04-05 21:13 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +def hex_str(data):
название такое себе, честно говоря (что с хекс-стрингом-то делается?) я бы parse_hex_str назвал

а что на экран вылезет, если какую-нибудь срань в аргумент ввести?
думаю, надо что-то довольно осмысленное выводить (как минимум, исходную строчку)
что-то вроде
`try:`
`return [int(x, 16) for x in data.strip().split()]`
`except ValueError as e:`
`logging.exception("Не смог прожевать строчку %s", строчка)`
`raise e`

ну и всё можно одной строкой сделать
`return [int(x, 16) for x in data.strip().split()]`

2022-04-05 21:22 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +def create_tcp_path(args):
а почему не
`return {'ip' : args.ip, 'port' : args.port}`

ну и ниже - соответственно

2022-04-05 21:24 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        client.connect("192.168.10.6", 1883)
а что за магические числа?
в переменную какую-нибудь вроде `MOSQUITTO_IP`

2022-04-05 21:27 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        resp = rpc_client.call('wb-mqtt-serial', 'port',
дебага бы
`logging.debug("рпс_клиент -> %s (%.2f timeout)", message, timeout)`

2022-04-05 21:33 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        rpc_parameters = args.path_create(args)
path_create чет - не очень название
я бы сделал:
`rpc_params = args.get_rpc_params(args)`
`rpc_params.update({'response_size' : modbus_resp_size, 'format' : 'HEX'})` и т.д.

2022-04-05 21:37 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        logging.info("Result code %d" % int(resp['result_code']))
кстати, логгинг умеет в леззи-форматтинг
тип вместо `logging.debug('mystr is %s' % mystr)` можно (и нужно) `logging.debug('mystr is %s', mystr)`

настоятельно рекомендую переделать везде
и почитать про логгинг
https://habr.com/ru/post/513966/

2022-04-05 21:41 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    tcp_subparser.add_argument("ip", type=str)
как-то валидируется?
и что на экран летит, если невалидный?

2022-04-05 21:50 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        logging.error('Wrong modbus parameters')
тут и дальше - трейсбек было бы неплохо видеть, думаю

с простым логгингом (в нашем случае) - можно изобрести что-то такое
`logging.error('Wrong modbus parameters', exc_info=(logging.root.level <= logging.DEBUG))`

2022-04-05 21:52 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        logging.error('Wrong modbus parameters')
ну и ниже - то же самое

а вообще - было бы хорошо сделать разный уровень дебага
тип -d - дебаг модбас_клиента; -dd - модбас_клиент + umodbus (у него же там свой логгер есть)

2022-04-05 21:54 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        resp = send_message(rpc_parameters, args.timeout)
кажется, try: можно сюда перенести сверху?

2022-04-05 21:57 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        logging.info(resp['error_msg'])
а что именно здесь лежит?
казалось бы, если всё ок - пустая строчка?

2022-04-05 22:00 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        result_code = ResultCode.OK
зачем его определять здесь, когда он из resp прилетает?

вдогонку:
1) все ли ексепшены, которые может выкинуть send_message учтены внизу?
2) может ли result_code прилететь не 0?

2022-04-05 22:07 UTC, vdromanov requested changes
резюмирую:

- _init_.py - лишний потому, что: работает __init__.py (два _); тебе он сейчас не нужен (__init__.py делает из папки с .py файлами - модуль)
- поправить по мелочи; больше логов
- подумать, обсудить:
- - аргументы, как в modbus_client
- - углубленный дебаг

2022-04-05 22:08 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    rtu_subparser.add_argument("serialport", type=str)
аналогично
если rpc там где-то просто тихо помирает, если порт неправильный - непорядок; непонятно же, что не так

2022-04-06 09:09 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +        result_code = ResultCode.OK
result_code - это для всего модбас-утилс. Если функция send_message в принципе выполнилась, значит основная функция утилиты (послать запрос, получить ответ) выполнена. Поэтому ResultCode.OK. 
Далее есть строки 
```
logging.info(resp['error_msg'])
logging.info("Result code %d" % int(resp['result_code']))
```
Вот тут уже выводится код результата самого запроса, плюс сообщение к нему, оба поля приходят ответом на rpc-запрос. Логичнее наверное поле назвать "msg" тогда...

2022-04-06 11:11 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    tcp_subparser.add_argument("ip", type=str)
Если указать невалидные данные, то serial скажет, что такого порта у него нет. Это касается и tcp параметров, и rtu.

2022-04-06 11:18 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +        resp = send_message(rpc_parameters, args.timeout)
Почему? Там ведь весь блок, начиная с create_message до send_message нуждается в обертке в try

2022-04-12 08:07 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +from exceptions import *
лучше так не делать из-за отвратной читаемости дальше по коду (непонятно, откуда берутся сущности)

лучше импортировать весь модуль, а дальше - `raise exceptions.RPCWrongParamSetError()`

2022-04-12 08:07 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    RPC_WRONG_RESP_LNGTH = -5
сокращение не по-питонски:)
`RPC_WRONG_RESPONSE_LEN`, например

2022-04-12 08:07 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    except (error, ModbusError) as err:
давай всё-таки, аналогично struct.error (как выше)

2022-04-12 08:08 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        if 0x01 <= args.func_type <= 0x04:
странненько, честно говоря, через >< делать
нагляднее - `if args.func_type in (0x01, 0x02, 0x03, 0x04)`
ну и дальше - аналогично

ну и в целом - общий месседж докапываний по стилю - добиться _максимальной читаемости_ даже с беглого взгляда

2022-04-12 08:08 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        logger.error('Wrong modbus parameters:\nFunction type %d\nSlave address %d\nStart address %d\nRead count %d\nWrite data %s',
@webconn топит за искоренение переноса строки в логах; т.е. надо примерно так:
```
logger.error('Wrong modbus parameters:')
logger.error('\tFunction type %d' % args.func_type)
```

Ну и везде просмотреть на предмет такого

2022-04-12 08:08 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +def check_port_parity_option(options):
парити были вроде none/even/odd

=>
```
if parity_port in ('none', 'even', 'odd'):
    return parity_port
else:
    try:
        return int(parity_port)
    except ValueError as e:
        logger.error("Ждём или none/even/odd, или tcp-порт")
        raise e
```
сюда комментов, мол у нас parity и tcp_port одним аргументом сделаны; и эту штуку прям в `type` в аргпарсере

ну а дефолтные парити/порт - поближе к parse_args обновлять

2022-04-12 08:09 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    parser.add_argument("-a", help="Slave address", type=parse_int,
про dec/hex-всеядность - не обсуждали?
тип, чтобы аргументы умели и в dec, и в hex

а чем `type = int` не годится? (тут и дальше); argparse же всё равно ай-ай выкинет

2022-04-12 08:09 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +                        default=1, dest="slave_addr", required=False)
а точно у modbus_client а адрес мог быть дефолтным? отстой же

2022-04-12 08:09 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    parser.add_argument("-r", help="Srart address", type=parse_int,
предполагаю, `start`)
ну и как-то не очень понятно; мб `First reg's addr`?

2022-04-12 08:09 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +                        choices=[1, 2, 3, 4, 5, 6, 15, 16],
посмотри, у умодбаса нет ли объявленных констант для fcod'ов модбаса?
если есть - переехать везде, где есть чиселки fcode

2022-04-12 08:09 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    parser.add_argument("-0", help="Slave address decrement",
а это - что такое?
не было ж у модбас_клиента, кажется
и хелп не очень помог)

2022-04-12 08:09 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    parser.add_argument('-b', help="Baudrate", type=parse_int,
choices сюда не нужны? там же 1200, 2400, 4800, 9600, ... 115200
тоже погляди в умодбас, вдруг есть константы/список допустимых

2022-04-12 08:10 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +                        default=1, dest="stop_bits", choices=[1, 2],
обсудите с @evgeny-boger  - мб s2 сделать по умолчанию?
в модбас_клиенте s1 по умолчанию - какая-то лажа, кажется

2022-04-12 08:10 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    parser.add_argument('-p', help="Parity {1,2} = 1 | Port = 502",
парити были none/even/odd, а не цифры - сейчас - также?

а вообще - проблема одного аргумента для разных режимов решается субпарсерами
сейчас предлагаю не переделывать, но посмотри в упдатер

2022-04-12 08:14 UTC, vdromanov requested changes
вдогонку - всё-таки, предлагаю dec/hex завезти сейчас
т.е. `parse_int` распадается на: `parse_parity_or_tcpport` (с реализацией +-, как расписал) и `parse_hex_or_dec`. Последняя будет `type`'ом у fcode, start_reg, data_to_write, slaveid (?) аргументов

2022-04-12 09:19 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +def check_port_parity_option(options):
А если укажут аргументы -mtcp -pnone? Изнутри type не увидим, что у нас, tcp или rtu

2022-04-12 09:23 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    parser.add_argument("-a", help="Slave address", type=parse_int,
У меня так работает, что если я сделаю type=int и укажу параметр, например -t0x0F,  он скажет что 
```
main.py: error: argument -t: invalid int value: '0x0F'
```
Поэтому пришлось вместо int написать parse_int

2022-04-12 09:25 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +                        default=1, dest="slave_addr", required=False)
Да, в старом клиенте так
https://wirenboard.com/wiki/Modbus-client#%D0%90%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9_%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8

2022-04-12 10:03 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    parser.add_argument('-b', help="Baudrate", type=parse_int,
Я об этом думала. В старом модбасе такого нет, что ввели - то и передается в настройки. Констант нет, так как микромодбас не включает в себя операции с физическими портами. Если нужно, можно просто внтури программы самим определить, например.

2022-04-12 10:06 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +                        default=1, dest="stop_bits", choices=[1, 2],
Вообще с учетом RPC все настройки RTU порта (кроме пути к нему) становятся рудиментом. Просто для совместимости. Потому что реальные настройки будут где то в serial. Так что не знаю...но в статье на вики значение по умолчанию 1. Спрашивать?

2022-04-12 10:29 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    parser.add_argument('-p', help="Parity {1,2} = 1 | Port = 502",
Да, фу, тут не цифры.
У меня были субпарсеры. С ними не получается повторить систему аргументов, либо я пока не поняла как 
Основная причина: раньше режим выбирался при помощи аргумента -m, то есть -mtcp или -mrtu было. Когда я делаю субпарсер, к нему обращение может быть только по имени, то есть либо tcp, либо tru, без -m. Можно сделать субпарсеры с именами -mtcp и -mrtu, но тогда валидные -m tcp и -m   tcp (несколько пробелов) уже не сработают.

2022-04-12 10:32 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    parser.add_argument("-a", help="Slave address", type=parse_int,
В общем то parse_int позволяет как раз hex/dec делать. А по-честному даже в двоичной и восьмиричной скушает (так как там в функции автоопределение системы счисления), но это фича разработчика.

2022-04-12 11:10 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    parser.add_argument('-b', help="Baudrate", type=parse_int,
> В старом модбасе такого нет

с большой вероятностью вангую, это есть в сишном libmodbus, на котором он написан
в общем, в choices надо

2022-04-12 12:19 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    parser.add_argument("-0", help="Slave address decrement",
В табличке старых параметров это есть, аргумент -0 указывает на декремент адреса ведомого
https://wirenboard.com/wiki/Modbus-client#%D0%90%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9_%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/exceptions.py
> +class RPCWrongParamSetError(Exception):
Я бы все эти исключения вокруг отдельных кодов возврата из RPC объединил в одно с параметром, а в идеале ещё и в `mqttrpc` перенёс. Плюс, в исключение можно положить объект с ответом RPC, там же ещё и сообщение об ошибке может лежать человекочитаемое.

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +        logger.error('Wrong modbus parameters:\nFunction type %d\nSlave address %d\nStart address %d\nRead count %d\nWrite data %s',
Действительно, топлю

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +        client.loop_stop()
Это не выбросит своего исключения, если цикл не запущен? (упали на `connect`, например)

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +        raise UModbusError from err
Мне не нравится тут название типа исключения. Его имя как будто отсылает к ошибке в библиотеке, а не в её использовании. Там есть реальные вещи, которые не покрываются только `ModbusError`?

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +            raise RPCWrongRespLngthError
Вот эту всю ёлку можно было бы решить, упаковав в одно исключение:

```python3
if rpc_result_code != RPCResultCode.OK:  # ну наверное
  raise RPCError(rpc_result_code)
```

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +        logger.error('Wrong RPC request parameters set\n%s',
Казалось бы, пользователь с этим ничего не сможет сделать, так что мы просто потеряли информацию об исключении в выводе программы. В таких ситуациях лучше выводить исключение как есть, я считаю

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +        logger.error('Wrong expected response length\nExpected %d\nActualy %d',
Переносы строки в логах плохо, а ещё `actual`, не `actualy`

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +    parser = argparse.ArgumentParser(conflict_handler='resolve')
А зачем нужен `resolve` тут? Мы ж один раз парсим аргументы без динамически создаваемого парсера

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +    options, unknown_options = parser.parse_known_args()
Нормально, что здесь второй раз вызов парсера?

2022-04-12 15:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +    set_write_data(parser, unknown_options, options)
Без этого не заработали аргументы вперемешку с данными, я так понимаю? А это вообще нужно? (умеет ли так modbus_client)?

2022-04-13 08:23 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +        client.loop_stop()
Нет, именно исключение нет. Процедура в этом случае возвращает ненулевой код ошибки, его можно игнорировать

2022-04-13 08:29 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    set_write_data(parser, unknown_options, options)
Да, проблема именно в этом была. В версиях питона >=3.7 есть функция parse_intermixed_args(), которая умеет работать с такими случаями, но у нас везде 3.5 используется, так что пришлось написать свой код.
Да, старый модбас-клиент так умеет
```
--debug -mrtu -pnone -s2 /dev/ttyRS485-1 -a1 -t0x0F -r0 -c 14 255 0 255 0 255 0 255 0 255 0 255 0 255 0
```
Вот эту команду я взяла из статьи на wiki. Если вызывать обычное parse_agrs() то argparse выбросит исключение, потому что не может понять аргументы "255 0 255 0 255 0 255 0 255 0 255 0 255 0".

2022-04-13 08:52 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +        raise UModbusError from err
Да, в микромодбасе есть такой недочет. ```ModbusError``` вызывается только если предоставили некорректные данные для записи. Все остальные исключения (если слишком большой адрес ведомого, адрес регистра и тд) имеют тип struct.error

2022-04-13 08:54 UTC, webconn commented on modbus_utils_rpc/main.py
> +    set_write_data(parser, unknown_options, options)
Что-то я читаю и не вижу, где тут перемешались аргументы

2022-04-13 08:58 UTC, webconn commented on modbus_utils_rpc/main.py
> +            raise RPCWrongRespLngthError
Перенесу из чатика: ещё лучше в исключение класть весь ответ (`resp`). Это хороший тон, вдохновиться можно библиотекой `requests`: https://docs.python-requests.org/en/master/_modules/requests/exceptions/

2022-04-13 12:55 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    set_write_data(parser, unknown_options, options)
Опциональные
```
--debug -mrtu -pnone -s2
```
Позиционные
```
/dev/ttyRS485-1
```
Опциональные
```
-a1 -t0x0F -r0 -c 14
```
Позиционные 
```
255 0 255 0 255 0 255 0 255 0 255 0 255 0
```
Да, я понимаю, выглядит так, будто должно работать, но нет. Даже вот такой запрос выполняется нормально
```
--debug -mrtu -pnone -s2 /dev/ttyRS485-1 255 0 255 0 255 0 255 0 255 0 255 0 255 0 -a1 -t0x0F -r0 -c 14
```
а первый - нет

2022-04-13 14:21 UTC, webconn commented on modbus_utils_rpc/main.py
> +    set_write_data(parser, unknown_options, options)
А, осознал. Окей

2022-04-13 14:36 UTC, webconn reviewed
Код нравится, пару мелочей можно подправить ещё. Пойду посмотрю, как это работает на практике :)

2022-04-13 14:36 UTC, webconn commented on modbus_utils_rpc/main.py
> +        if error.result_code == RPCResultCode.RPC_WRONG_PARAM_SET:
Думаю, можно всё это в отдельную функцию отправить, а то получилась одна и очень развесистая. Пусть принимает на вход исключение и возвращает result_code

2022-04-13 14:36 UTC, webconn commented on modbus_utils_rpc/main.py
> +        logger.error('Wrong modbus parameters:')
Вот это всё тоже в отдельную функцию можно

2022-04-13 14:41 UTC, webconn commented on debian/control
> +Depends: python3, ${misc:Depends}, python3-umodbus (>=1.0.4-1+wb1), python3-paho-mqtt (=1.4.0), python3-mqttrpc(>=1.1.2)
Тут стоит строгое равенство около версии `python3-paho-mqtt`, оно не даёт установить пакет, потому что в репозитории `1.4.0-1`. Вообще равенство лучше не применять никогда, только для пакетов из одного исходника и в виде `my-package (= ${binary:Version})`

2022-04-13 15:02 UTC, ekateluv commented on debian/control
> +Depends: python3, ${misc:Depends}, python3-umodbus (>=1.0.4-1+wb1), python3-paho-mqtt (=1.4.0), python3-mqttrpc(>=1.1.2)
Кстати, насчет paho. Такое равенство стоит, потому что на версиях новее чем 1.4.0 не будет работать связка с mqtt-rpc. Для создания потока там дергается имя клиента из поля объекта paho, в новых версиях этого поля больше нет, имя достается по-другому. Если версия пахо будет больше, чем 1.4.? то придется и mqtt-rpc как то адаптировать

2022-04-13 15:04 UTC, webconn commented on debian/control
> +Depends: python3, ${misc:Depends}, python3-umodbus (>=1.0.4-1+wb1), python3-paho-mqtt (=1.4.0), python3-mqttrpc(>=1.1.2)
Если ломается mqtt-rpc, то зависимость надо прописывать там в духе `(< версия.в.которой.всё.сломалось)` и ставить задачу на адаптацию

2022-04-13 15:18 UTC, webconn reviewed
Попробовал запустить на контроллере, всплыли вот такие истории

2022-04-13 15:18 UTC, webconn commented on debian/control
> +Depends: python3, ${misc:Depends}, python3-umodbus (>=1.0.4-1+wb1), python3-paho-mqtt (=1.4.0), python3-mqttrpc(>=1.1.2)
Ещё тут не хватило зависимостей при запуске от `python3-six` и `python3-pkg-resources` (последний нужен для entrypoint-а, который ты прописала в `setup.py`; я бы советовал лучше сделать свой маленький скриптик, как тут: https://github.com/wirenboard/wb-update-manager/blob/master/bin/wb-release , ибо так запускается гораздо быстрее, стандартные питоновые entrypoint-ы очень много всего лишнего делают).

И назвать этот entrypoint стоит как `modbus_client.rpc` или как-то так, чтобы по автодополнению от `modbus_client` разрешался

2022-04-13 15:18 UTC, webconn commented on modbus_utils_rpc/main.py
> +import exceptions
```py3
from . import exceptions
````
а то он ищет этот модуль глобально, если ходить через entrypoint

2022-04-13 15:40 UTC, webconn reviewed
В общем, оно почти заработало, я смог прочитать регистры, но записать в holding не смог, команда была такая (на 188 адресе висит wb-msw v3) (вместо `-mtcp` должно быть `-mrtu`, но это из-за опечатки в коде):

```
modbus-utils-rpc --debug -mtcp -pnone -b9600 -s2 -a 188 /dev/ttyRS485-1 -t0x06 -r 0x78 10
```

2022-04-13 15:40 UTC, webconn commented on modbus_utils_rpc/main.py
> +        logger.info('Error_message: %s', rpc_response['error_msg'])
Получается, что если запустить скрипт без флага `--debug`, это тоже выводится. Точно можно переносить в `debug`

2022-04-13 15:40 UTC, webconn commented on modbus_utils_rpc/main.py
> +        logger.info('Result code: %d', rpc_result_code)
И это тоже в `debug`, без флага не нужно

2022-04-13 15:40 UTC, webconn commented on modbus_utils_rpc/main.py
> +        get_port_params = get_rtu_params
Тут перепутаны `tcp` и `rtu`, и ниже тоже :)

2022-04-13 15:40 UTC, webconn commented on modbus_utils_rpc/main.py
> +            logger.debug('Read data: [%s]',
А вот это как раз надо выводить в `stdout` не через логгер, а так, как это делает `modbus_client`, например, вот так:

```
# modbus_client -mrtu -pnone -b9600  -s2 -a 188 /dev/ttyRS485-1 -t0x04 -r 104 -c2
SUCCESS: read 2 of elements:
        Data: 0x0001 0x4947
```

Аналогично для записи:

```
# modbus_client -mrtu -pnone -b9600  -s2 -a 188 /dev/ttyRS485-1 -t0x06 -r 0x78 10
SUCCESS: written 1 elements!
```

Вывод при добавленном флаге `--debug` желательно делать в `stderr` (хоть оригинальная утилита и пишет в `stdout`) и сделать его по возможности похожим, особенно в плане формата вывода сообщений:

```
 modbus_client  --debug -mrtu -pnone -b9600  -s2 -a 188 /dev/ttyRS485-1 -t0x04 -r 104 -c2
Opening /dev/ttyRS485-1 at 9600 bauds (N, 8, 2)
[BC][04][00][68][00][02][EB][3A]
Waiting for a confirmation...
<BC><04><04><00><00><00><58><97><75>
SUCCESS: read 2 of elements:
        Data: 0x0000 0x0058
```

2022-04-13 16:53 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +        logger.info('Error_message: %s', rpc_response['error_msg'])
Это единственные строчки .info. Если убрать это в дебаг, то тогда никакого вывода не будет в консоль, только main вернет какой то result_code и все.
В старом модбас утилсе похожие по смыслу строки не были закрыты в дебаг
https://github.com/wirenboard/modbus-utils/blob/b71e3814850a38d75357e821e0a1fb7084d49dc8/modbus_client/modbus_client.c#L367

2022-04-14 08:33 UTC, webconn commented on modbus_utils_rpc/main.py
> +        logger.info('Error_message: %s', rpc_response['error_msg'])
Так это неправильно, что вывода никакого не будет. `modbus_client` ещё выводит результат операции

2022-04-14 21:19 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    # TODO: add RTU mode support to be able to work with ports unknown to wb-serial
если это оно - тут идея: ходить **через сериал**, но в любой порт (а не только те, что прописаны в конфиге и опрашиваются)

если контекст такой - тудушку надо понятнее написать, а то время пройдёт, и все головы ломать будут

2022-04-14 21:19 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +        string: mesage
спелл-чекер наверняка есть для вскода

2022-04-14 21:19 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +            slave_address -= 1
а точно слейв адрес надо уменьшать?
модбас_клиент же старт_адрес уменьшал

2022-04-14 21:22 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +def set_write_data(parser, unknown_options, options):
в целом, функция скорее не нравится:

- напечатает нам только первый несъеденный ключ запуска, а было бы хорошо - напечатать все
- зачем getattr? `options.write_data` же можно?
- **неявно** обновлять какие-то данные - такое себе. Все, заглядывающие в код, будут идти в мейн и думать, а откуда же собирается write_data

В целом - если что-то можно сделать прямо на месте без большого вреда для читаемости - лучше поступать именно так. + передавая в функции изменяемые и неизменяемые объекты, можно очень увлекательно стрелять по ногам

итого, предлагаю эту функцию убрать; в мейне собирать `write_data` и список `startswith('-')` из того, что не прожевал argparse

2022-04-18 09:45 UTC, webconn commented on modbus_utils_rpc/main.py
> +from modbus_utils_rpc import exceptions
А через точку не работает?

2022-04-18 09:45 UTC, webconn commented on modbus_utils_rpc/main.py
> +MOSQUITTO_IP = "192.168.10.6"
Внезапно :)

2022-04-18 09:47 UTC, webconn commented on modbus_utils_rpc/main.py
> +MOSQUITTO_IP = "192.168.10.6"
Кстати, наверное, стоит добавить аргументов про это, чтобы можно было подключаться к удалённым брокерам

2022-04-18 10:07 UTC, webconn reviewed
Попробовал, вроде работает хорошо, мне нравится. Предлагаю ещё добавить аргументов для настройки соединения с RPC-сервером и надо вливать

2022-04-18 10:07 UTC, webconn commented on modbus_utils_rpc/main.py
> +        logger.debug('Connecting with broker %s:%s',
`Connecting to`

2022-04-18 10:07 UTC, webconn commented on modbus_utils_rpc/main.py
> +            print('\rNew value:', ''.join("0x{:02x}".format(data)))
В оригинальном modbus_client вроде new value не выводился, можно убрать. К тому же начинается с символа `\r` почему-то

2022-04-18 10:58 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +MOSQUITTO_IP = "192.168.10.6"
Забыла поменять, уберу сейчас. Это я так с хоста отлаживаюсь
Хорошо, добавлю

2022-04-18 11:05 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +from modbus_utils_rpc import exceptions
Да, с точкой не могла запуститься, 
Позже я почитала стековефлоу https://stackoverflow.com/a/28154841
И пеп8 https://z5h64q92x9.net/proxy_u/en-ru.ru.92c59502-625d43cc-cd92d396-74722d776562/https/peps.python.org/pep-0008/#imports
И решила использовать абсолютный импорт

2022-04-18 11:10 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +            print('\rNew value:', ''.join("0x{:02x}".format(data)))
Насчет \r, я вот на это ориентировалась https://github.com/wirenboard/modbus-utils-rpc/pull/1#discussion_r848115934
Как я для себя поняла: сначала основная информация, потом добавочная с отступа

2022-04-18 11:14 UTC, webconn commented on modbus_utils_rpc/main.py
> +            print('\rNew value:', ''.join("0x{:02x}".format(data)))
Да, но только там должно было быть `\t` :)

2022-04-18 20:15 UTC, webconn approved these changes

2022-04-19 12:58 UTC, vdromanov approved these changes

2022-04-19 13:03 UTC, merged