Feature/50416 modbus scanner
wirenboard/modbus-utils-rpc pull request #3
Opened 2022-07-13 12:14 UTC by ekateluv

Немного переименовала старый пакет, то что касается обычных modbus-запросов по rpc теперь называется везде modbus_client, а все что касается сканирования - modbus_scanner

2022-07-15 05:08 UTC, vdromanov commented on modbus_scanner_rpc/main.py
> +        "path": "/dev/ttyRS485-2",
зачем захардкоженно?

если это - только прототип - неплохо бы такое в описание к PR добавлять. Сейчас описание - не очень:(

2022-07-15 05:08 UTC, vdromanov commented on modbus_scanner_rpc/main.py
> +    rpc_client.call("wb-mqtt-serial", "port", "Load", create_message("00600198", 0), 500.0)
а что тут происходит?
магическое число какое-то

2022-07-15 05:08 UTC, vdromanov commented on modbus_scanner_rpc/main.py
> +def continue_scan(rpc_client):
зачем нужен continue? (так тонко намекаю на докстринги и какое-то понятное именование функций)

тем более, наша внутренняя магия - точно надо докать

ну и сразу здесь всё напишу:
магические числа; адрес(?) захардкожен; ручками пейлоад разбираешь (модбасные еррор-коды не обрабатываются, кстати?)
=> если это - суперпрототип (с начальством утверждено) - так и написать; иначе - всё плохо

кстати, umodbus умеет ответ разбирать? (на fun/err_code, payload, ...)

2022-07-15 05:10 UTC, vdromanov requested changes
если это - только прототип - всю неочевидную магию описать в докстрингах; магические числа - лучше в переменные/константы

цель - чтобы человеку, не знакомому с новым модбасом, было в общих чертах понятно, что вообще происходит

а так - выглядит неплохо!

2022-07-15 05:10 UTC, vdromanov commented on modbus_scanner_rpc/main.py
> +    scan_message = bytearray.fromhex(response["response"].lstrip("ff"))
а если пустой?

2022-07-15 05:12 UTC, vdromanov commented on modbus_scanner_rpc/main.py
> +        if not scan_message.startswith(bytearray.fromhex("0060")):
ну и я бы логику разбора response от нового модбаса вытащил в отдельную функцию
(но не особо настаиваю, если прототип)

2022-07-15 05:15 UTC, vdromanov commented on modbus_scanner_rpc/.vscode/launch.json
> +{
а точно надо в репу класть?

2022-07-15 08:28 UTC, ekateluv commented on modbus_scanner_rpc/.vscode/launch.json
> +{
Нет, не точно

2022-07-15 09:41 UTC, webconn requested changes
Резюме - ради тестовой версии скрипта переименовывать пакеты точно не стоило )

Наверное, я высказался недостаточно конкретно. Хотелось просто на пример такого скрипта посмотреть, без пакетизации, всё равно сейчас это отгружать нельзя в таком виде

2022-07-15 09:41 UTC, webconn commented on modbus_scanner_rpc/.vscode/launch.json
> +{
Точно не стоит

2022-07-15 09:41 UTC, webconn commented on debian/control
> +Package: python3-modbus-client-rpc
Ай, не надо так делать, пожалуйста. Там концов потом не сыщешь, при обновлении потеряется старый пакет и всё сломается.

Вообще не вижу причин, чтобы новый сканер не положить в пакет с названием `modbus_utils_rpc` (как `modbus_utils_rpc.wb_scanner`, например)

2022-07-15 09:41 UTC, webconn commented on modbus_scanner_rpc/main.py
> +        "path": "/dev/ttyRS485-2",
И да, если мы делаем прототип, то надо сделать так, чтобы он не разъехался пользователям. Для этого есть такие варианты:

1) делаем тут директорию `examples` и кладём туда отдельным скриптом, мержим в `main`, в пакеты никак не добавляем, потом при случае переносим;
2) делаем ветку под большую разработку функционала, и в неё инкрементами добавляем сначала прототип, потом конечную версию утилиты

2022-07-18 10:33 UTC, ekateluv commented on modbus_scanner_rpc/main.py
> +        "path": "/dev/ttyRS485-2",
Давайте второй вариант? Могу первести PR в драфт.

2022-07-18 10:43 UTC, ekateluv commented on debian/control
> +Package: python3-modbus-client-rpc
Почему я так сделала: в папку /bin/ был положен скрипт, который вызывается по имени modbus_client_rpc. При этом весь репозиторий назывался modbus_utils_rpc и сам как бы пакет модбас-клиента тоже оказался назван modbus_utils_rpc. Теперь же, когда к сущности "модбас утилс" оказался добавлен "модбас сканнер", стало очевидно что старый код логичнее называть "модбас клиент". Плюс, это код еще никуда далеко не уехал, ни в какие другие проекты не просочился, я решила переименовать

2022-07-18 10:45 UTC, webconn commented on debian/control
> +Package: python3-modbus-client-rpc
Тут изначальный смысл был в том, чтобы привлечь людей использовать новую утилиту за счёт похожести на старую, в том числе названием. К тому же, `modbus_client` и `modbus_scanner` вполне могут быть частями пакета `modbus_utils`, не ломая смысл слов

2022-08-19 13:43 UTC, webconn requested changes
Тут всё ещё надо перестать переименовывать пакеты и убрать лишние файлы. Инкрементировать версию тоже не нужно. В общем, в этом PR по-хорошему должен лежать ровно один `.py`-файл, в котором будет небольшая утилита, умеющая сканировать устройства через RPC, всё.

2022-09-14 14:41 UTC, ekateluv commented
Новый PR после ребейза
https://github.com/wirenboard/modbus-utils-rpc/pull/5

2022-09-14 14:41 UTC, closed without merging