Error handling using mqttrpc library
wirenboard/modbus-utils-rpc pull request #4
Opened 2022-07-20 05:33 UTC by ekateluv

Изменила процесс обработки ответа на запрос в соответствии с библиотекой mqttrpc. Теперь исключения об ошибках выбрасывает сама библиотека

2022-07-22 00:01 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    if "response" in response:
in response.keys() лучше бы

2022-07-22 00:01 UTC, vdromanov commented on modbus_utils_rpc/main.py
> +    logger.debug("Error message: %s", error.error_message)
дебаги бы  в какой-нибудь print_error выделить
одинаковые же здесь и ниже

2022-07-22 00:02 UTC, vdromanov approved these changes
эту пару мелочей поправить бы; а так - всё хорошо!

2022-07-22 18:21 UTC, webconn requested changes
И у тебя ещё тесты попадали

2022-07-22 18:21 UTC, webconn commented on modbus_utils_rpc/main.py
> +def send_message(args, message):
Было лучше: более конкретные значения в качестве аргуметов функций предпочтительней, если их не очень много. Здесь - не много

2022-07-22 18:21 UTC, webconn commented on modbus_utils_rpc/main.py
> +    logger.debug("Error message: %s", error.error_message)
Да, стоит сделать. А вообще похоже, что если тут не пытаться вычленить `USER_INPUT_ERROR`, то `handle_rpcparserror` будет отдельно не сильно отличаться от этой

2022-07-22 18:21 UTC, webconn commented on modbus_utils_rpc/main.py
>          result_code = ResultCode.USER_INPUT_ERROR
Не, `SERVER_ERROR` - это не ошибка в пользовательском вводе, это тоже `OPERATION_ERROR`

2022-07-26 20:24 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +    if "response" in response:
Поправила, но почему?

2022-07-29 04:48 UTC, ekateluv commented on modbus_utils_rpc/main.py
> +def send_message(args, message):
Верну, но agrs в аргументах все равно придется оставить, они нужны на случай если возникнет исключение

2022-07-29 04:57 UTC, ekateluv commented on modbus_utils_rpc/main.py
>          result_code = ResultCode.USER_INPUT_ERROR
Библиотека rpc имеет три типа ошибок:
```
    E_RPC_PARSE_ERROR = -32700
    E_RPC_SERVER_ERROR = -32000
    E_RPC_REQUEST_TIMEOUT = -32600
```
Первая - когда мы не смогли распарсить ответ (то есть там какой то неожиданный JSON пришел), второй когда выполнение запроса завершилось неудачно, третий когда выполнение запроса словило таймаут на стороне исполнителя. Фактически, под вторую ошибку попадают не только случаи, когда сервер сам по себе почему то не смог выполнить запрос, а также случаи, когда запрос выполнить невозможно вследствие ввода неверных данных, например, запрос несуществующего порта. Тут так получается, что библиотека не дает мне возможности различить, что на самом деле там произошло

2022-08-16 10:03 UTC, webconn commented on modbus_utils_rpc/main.py
>          result_code = ResultCode.USER_INPUT_ERROR
Строго говоря, входные данные RPC и пользовательский ввод - это не одно и то же :)

Когда (если) библиотека научится различать внутренние ошибки и ошибки вследствие неправильных параметров, можно будет тут это учесть, а прямо сейчас проще свести всё к `OPERATION_ERROR`. Да, немного нарушается консистентность, но на пользовательский опыт (пока) не влияет.

2022-08-19 12:40 UTC, webconn commented on modbus_utils_rpc/main.py
> +def send_message(args, message):
А зачем, всё же? Прелесть исключений как раз в том, что их можно обработать выше по стеку и не тащить ради них контекст вниз

2022-08-19 13:30 UTC, webconn commented on modbus_utils_rpc/main.py
> +    if "response" in response:
Тоже не понимаю, чем это лучше. `keys` вернёт список, и поиск по нему - O(n),  а так это поиск по хеш-таблице со всеми вытекающими О(1): https://stackoverflow.com/questions/1602934/check-if-a-given-key-already-exists-in-a-dictionary/30527984#30527984

Поиск ключа в словаре в питоне так и делается.

Не надо менять (изменение и не заехало).

2022-08-19 13:34 UTC, webconn approved these changes
По-моему хорошо, не будем тратить время на перестановку букв

2022-08-19 13:43 UTC, merged