Modbus scanner
wirenboard/modbus-utils-rpc pull request #5
Opened 2022-09-14 14:33 UTC by ekateluv

Скрипт, сканирующий все устройства на модбас-шине

2022-09-15 11:02 UTC, webconn commented on modbus_scanner_rpc/main.py
> +    print("SCAN INIT")
Я бы это в логгер писал с уровнем debug. Считаю, что на практике команда должна в stdout выдавать только полезную инфу, в нашем случае - список найденных устройств, всё остальное - детали реализации. Касается этого места и почти всех остальных `print`-ов в скрипте

2022-09-15 11:02 UTC, webconn commented on modbus_scanner_rpc/main.py
> +    except redundancy_check.CRCError as error:
Касается только первой строчки в `try`, можно наверх перенести. И в целом не уверен, что нужно перепаковкой заниматься

2022-09-15 11:02 UTC, webconn commented on modbus_scanner_rpc/main.py
> +            raise exceptions.RPCClientTimeoutError from error
На будущее, лучше избавиться от внутренних исключений, где они не нужны, дабы не заниматься этой перепаковкой. Это бойлерплейт, никому пользы не приносит, а код раздувает

2022-09-15 14:06 UTC, webconn requested changes
Можешь приложить ещё пример вывода утилиты сюда?

2022-09-15 14:06 UTC, webconn commented on modbus_scanner_rpc/main.py
> +        print("Scan error while parsing answer", "".join("{:02x}".format(x) for x in scan_message))
Не в `logger.error` лучше бы это положить?

2022-09-16 09:04 UTC, ekateluv commented
Без дебага
```
Found device with SN  fe48b6f5 4266178293 modbus address  11
Found device with SN  fe5f953c 4267676988 modbus address  8
Found device with SN  fe87f4fb 4270322939 modbus address  25
Found device with SN  fe88800b 4270358539 modbus address  75
Found device with SN  fec2395a 4274141530 modbus address  10
Found device with SN  fed260d2 4275200210 modbus address  207
Found device with SN  fed2a1ce 4275216846 modbus address  49
Found device with SN  fed2f90b 4275239179 modbus address  76
```

С дебагом
```
Connecting to broker 192.168.0.6:1883
Scan init
RPC Client -> {'path': '/dev/ttyRS485-2', 'response_size': 0, 'format': 'HEX', 'msg': 'FD600109F0', 'total_timeout': 10000}, 10000 ms
Response: 
Scan next
RPC Client -> {'path': '/dev/ttyRS485-2', 'response_size': 60, 'format': 'HEX', 'msg': 'FD600249F1', 'total_timeout': 10000}, 10000 ms
RPC Client <- {'response': 'fffffffffffffffffffffffffffffffffffffffffffffd6003fe1242014463f8'}
Response: fffffffffffffffffffffffffffffffffffffffffffffd6003fe1242014463f8
Found device with SN  fe124201 4262609409 modbus address  68
Scan next
RPC Client -> {'path': '/dev/ttyRS485-2', 'response_size': 60, 'format': 'HEX', 'msg': 'FD600249F1', 'total_timeout': 10000}, 10000 ms
RPC Client <- {'response': 'fffffffffffffffffffffffffffffffffffffffffd6004c9f3'}
Response: fffffffffffffffffffffffffffffffffffffffffd6004c9f3
Scan end
```

2022-09-16 13:27 UTC, webconn approved these changes

2022-09-19 06:58 UTC, merged